name: Update Google Sheet

on:
  push:
    branches:
      - main

jobs:
  update-google-sheets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install googleapis google-auth-library

    - name: Update Google Sheets
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        node <<EOF
        const { google } = require('googleapis');
        const credentials = JSON.parse(process.env.GOOGLE_CREDENTIALS);

        const auth = new google.auth.GoogleAuth({
          credentials,
          scopes: ['https://www.googleapis.com/auth/spreadsheets'],
        });

        const sheets = google.sheets({ version: 'v4', auth });

        async function updateSheet() {
          const spreadsheetId = '10QhDmqimECd8sRPNMOTAvTXU_-lHG3to1mWx-qx9xNU';

          const gachaResults = [
            { date: '2025-01-22', user: 'User123', card: 'Card A', rarity: 'Rare' },
            { date: '2025-01-22', user: 'User456', card: 'Card B', rarity: 'Ultra Rare' },
          ];

          const values = gachaResults.map(result => [
            result.date,
            result.user,
            result.card,
            result.rarity,
          ]);

          await sheets.spreadsheets.values.append({
            spreadsheetId,
            range: 'Sheet1',
            valueInputOption: 'RAW',
            insertDataOption: 'INSERT_ROWS',
            resource: { values },
          });

          console.log('Google Sheet Updated!');
        }

        updateSheet().catch(console.error);
        EOF
